language: java

os:
  - linux
  - osx

matrix:
  include:
    - os: linux
      dist: trusty
      jdk: oraclejdk8
  exclude:
    - os: osx
      jdk: oraclejdk11
    - os: osx
      jdk: oraclejdk12
    - os: osx
      jdk: openjdk12

jdk:
  - oraclejdk11
  - oraclejdk12
  - openjdk11
  - openjdk12

cache:
  directories:
    - $HOME/.m2